### ISSUE TITLE
Crash in 1.17

### ISSUE THREAD

**Issue by MarioAndWeegee3** [SFort/MC-lengthyladders#5]
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.method_10234(class_2378.java:176)
	at net.minecraft.class_2378.method_34031(class_2378.java:275)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_2378.<clinit>(class_2378.java:274)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	... 7 more
Caused by: java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:item / minecraft:ladder] at different raw IDs (249, 186)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$bbd000$setPre(class_2370.java:650)
	at net.minecraft.class_2370.method_31051(class_2370.java)
	at net.minecraft.class_2370.method_10273(class_2370.java:72)
	at net.minecraft.class_2348.method_10273(class_2348.java:28)
	at net.minecraft.class_2378.method_10231(class_2378.java:434)
	at net.minecraft.class_1802.<clinit>(class_1802.java:1156)
	... 13 more
```

**Comment by SFort** [comment]
ye that feature was released a bit too soon i really need to learn to use the beta tag
thanks for the report

**Comment by SFort** [comment]
i was actually unable to reproduce the issue. so while i can't be certain. i am fairly confidnt this will fix it if it doesn't please re-open
